repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries, "99", --wrap-descriptions, "92"]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          # TODO: setme point to your pylintrc
          - --rcfile=~/.pylintrc

  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.5.0
  #   hooks:
  #     - id: nbstripout
  #       description: "nbstripout: strip output from Jupyter and IPython notebooks"
  #       entry: nbstripout
  #       language: python
  #       types: [jupyter]
